language: android
sudo: required
dist: trusty
jdk: oraclejdk8

addons:
  sonarcloud:
    organization: "zhiwei1990-github"
    token:
      secure: "Ev02Xqtdw8ddUdnfxkoz7zJ2jLHO7o5nmt5KrATMLj5pbKLsJo0Fc+dZuLhxtqJ1iaAoLf85gD32WBMA5ojbFzNNyFshgocMgHSf56xektBLhNZ1BXsA4bERxVpAKv+WdX9JiKfVm5n5b75oqN1o4QEFr9YYhGI4wlbnl3W0OTOSRE9bK/7EwB79nhcOidOctwIC9UI6lRY5CcGwUso2AzdfKCgtJ5RMz5pmOoZGZJfB8Vl04R8ohqUHjIJsLwhSrt+/xF/vMj2RapGF409NQY4q9Tz9f++OTc35oCZoPkHKRPxc8cc6qL/PtErAFa9u9cFslq4wis2xmxQrZ+2d2hWtMQIIfkxkkwZTst/EkQDLMl8NMqWkm3y9nRbhHKJkklDzIBjN3ZmSYlXuX1ZG29HTGXous0g1DuyYCL45jI9d/4FRJp7IMxfy+5zC6aABV/bGZijKLg/98p6plDx0xzy/PbL6ZofzK7it2ZmuGu+2uedgLGKf559gGz2kPjaLT7mwnjufGtb2QXgoJ2uvcge8cxjFCFFSs2eq/JsT0wcwObwoR43gOHJJNbF6zcrlqm2tB8bOah/wtjuLTwZ9xwTSPwJb1WglXwd69pCys8Sp0OMMddgk34JQBSXgwuNFhENjBOJkyjjKyHBL0QmBo/1bvKVWmCRXVXWl3WwhqLQ="

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
  - rm -rf $HOME/.android/build-cache/*
  - rm -rf $HOME/.sonar/cache/*

cache:
  directories:
    - '$HOME/.gradle/caches/'
    - '$HOME/.gradle/wrapper/'
    - '$HOME/.android/build-cache'
    - '$HOME/.sonar/cache'

env:
  global:
    - ANDROID_API=29
    - ANDROID_BUILD_TOOLS=29.0.3

android:
  components:
    - tools
    - tools # Running this twice get's the latest build tools (https://github.com/codepath/android_guides/wiki/Setting-up-Travis-CI)
    - platform-tools
    - android-${ANDROID_API}
    - build-tools-${ANDROID_BUILD_TOOLS}
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - chmod +x ./gradlew
  - "./gradlew clean test build"
  - sonar-scanner

#before_install:
#  - openssl aes-256-cbc -K $encrypted_cc48737a0442_key -iv $encrypted_cc48737a0442_iv
#  - in githubKeyStore.jks.enc -out githubKeyStore.jks -d
#deploy:
#  provider: releases
#  api_key:
#    secure: VERCb+2U7BcgZSyim5vkgdL0s8BGPcEOsqvpzzUjZjdYTEItB2SNCKUhbn0ugNYUFmFTacZ+NPi6veUQwqWrSPLQPuJe6ePZeOAaYgBrGGkeYnJ2EsnADYKiJypEsICWYScdKk6BSKjnYn6KaPAN2MvPiMfaLIDEOLmLpHR+hcC8sohl5by7LFySFI9Iqzx/Qga0ZmnviBIULO3ttyGA6r6jOpt4qKCEmcmywU8j8WzoMA4M8OQBamkSh1EvxUIujAJWle/ccOn7J5jx53o6pKfOeKKebEnZ25I4SDzGAQZ+bv98JlBTwqkbdWB+Ud5w3eZrNim5FqFOc7xVKjCW3Lylljj1Yt/k/9GuhpieIH21hYsKivTYzsINgPk1NC6Sjv7jBoyN3WkuPYJ9+z1JTqIrD6w6xIPsQlYEWZi4mFtvqVKofY+zX4vVE6xGEhRMfhjjw2luE2AXLGC2sRU9NIntikx+srnjp5hb8bCnbPjV+Y+Nu6KkDuU1O+tGlVr29p95fo5leaM/uFNB5vpyZHdAfL0utDcv3axGJITRJNZRPseQNlY3H49/booOvsoqk4jngsnPhZAcugkB2KYyI3BRdnTkNxS7LAHNt2JFxmnE/7BU1/IdnBJf+Vx3AL84JX6lkz6YyiAzhuMOQxpocFOQlpwRiRBqmRVx3xWDphE=
#  file: app/build/outputs/apk/apk-release.apk
#  # 这句手动添加
#  skip_cleanup: true
#  on:
#    repo: zhiwei1990/android-jetpack-demo
#    # 这句手动添加
#    tags: true
